

//请求下载文件
#define  WEBSERVER_NOTIFICATION_REQUEST_DOWNLOAD_FILE    @"WEBSERVER_NOTIFICATION_REQUEST_DOWNLOAD_FILE"
//下载IPA完毕
#define  WEBSERVER_NOTIFICATION_DOWONLOAD_FILE_COMPLETE    @"WEBSERVER_NOTIFICATION_DOWONLOAD_FILE_COMPLETE"
